name: 🚀 CoHack Journey

on:
  push:
    branches: main
    paths-ignore: ['**.md', 'docs/**']
  workflow_dispatch: 

env:                                    # Workflow-level
  WORKSHOP_NAME: "GH-200 CoHack"
  TRAINER: "Himanshu Kumar"

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Step with timeout
        timeout-minutes: 2
        run: |
          echo "This step must complete in 2 mins"
          echo "Completed within time!"

  
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6
      - name: 🎨 Use Custom Banner Action
        uses: ./.github/actions/ascii-banner.yml
        id: banner
        with:
          text: "CoHack!"
          font: "digital"
      - name: Show Banner Output
        run: echo "Generated banner output captured in outputs!"

