name: 🚀 CoHack Journey

on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule: 
    - cron: '0 9 * * 1'
  workflow_dispatch: 

env:                                    # Workflow-level
  WORKSHOP_NAME: "GH-200 CoHack"
  TRAINER: "Himanshu Kumar"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true           # Cancel older runs on same branch


jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Step with timeout
        timeout-minutes: 2
        run: |
          echo "This step must complete in 2 mins"
          sleep 30
          echo "Completed within time!"
